version: '3'
services:
  kafka-rest:
    image: golang:1.14-alpine
    restart: unless-stopped
    volumes:
      - .:/go/kafka-rest
    working_dir: /go/kafka-rest
    ports: 
      - 8080:8080
    command: go run main.go
